package gui;

import javax.swing.*;
import java.awt.*;

public class AdbSettingsWindow {
    private JPanel panel1;
    private JTextField adbPath;
    private JCheckBox saveAdbPathCheckBox;

    public JPanel getPanel1() {
        return panel1;
    }

    public JTextField getAdbPath() {
        return adbPath;
    }

    public void setAdbPath(JTextField adbPath) {
        this.adbPath = adbPath;
    }

    public JCheckBox getSaveAdbPathCheckBox() {
        return saveAdbPathCheckBox;
    }

    public void setSaveAdbPathCheckBox(JCheckBox saveAdbPathCheckBox) {
        this.saveAdbPathCheckBox = saveAdbPathCheckBox;
    }

    public void setPanel1(JPanel panel1) {
        this.panel1 = panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.NORTH);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel2.add(panel3, BorderLayout.CENTER);
        adbPath = new JTextField();
        adbPath.setColumns(20);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(adbPath, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Specify the path to adb.exe");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(label1, gbc);
        saveAdbPathCheckBox = new JCheckBox();
        saveAdbPathCheckBox.setText("save");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(saveAdbPathCheckBox, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(spacer1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
