package gui;

import javax.swing.*;
import java.awt.*;

public class WindowDesigner {
    private AppWindow data;
    private JPanel panel1;
    private JTextField fromField;
    private JTextField toField;
    private JTextField fileField;
    private JCheckBox saveCheckBox;
    private JButton refreshButton;
    private JButton pushButton;
    private JButton checkButton;
    private JTextArea textArea1;

    public AppWindow getData() {
        return data;
    }

    public JPanel getPanel1() {
        return panel1;
    }

    public JTextField getFromField() {
        return fromField;
    }

    public JTextField getToField() {
        return toField;
    }

    public JTextField getFileField() {
        return fileField;
    }

    public JCheckBox getSaveCheckBox() {
        return saveCheckBox;
    }

    public JButton getRefreshButton() {
        return refreshButton;
    }

    public JButton getPushButton() {
        return pushButton;
    }

    public JButton getCheckButton() {
        return checkButton;
    }

    public JTextArea getTextArea1() {
        return textArea1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel1.add(panel2, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setText("From");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel2.add(spacer1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("To");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("File");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label3, gbc);
        fromField = new JTextField();
        fromField.setColumns(10);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(fromField, gbc);
        toField = new JTextField();
        toField.setColumns(10);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(toField, gbc);
        fileField = new JTextField();
        fileField.setColumns(10);
        fileField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(fileField, gbc);
        saveCheckBox = new JCheckBox();
        saveCheckBox.setText("Save");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(saveCheckBox, gbc);
        refreshButton = new JButton();
        refreshButton.setText("Start");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(refreshButton, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer2, gbc);
        pushButton = new JButton();
        pushButton.setText("Push");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(pushButton, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new CardLayout(0, 0));
        panel1.add(panel3, BorderLayout.CENTER);
        textArea1 = new JTextArea();
        textArea1.setEditable(false);
        textArea1.setEnabled(true);
        textArea1.setLineWrap(false);
        textArea1.setRows(0);
        panel3.add(textArea1, "Card1");
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
